django_list/urls.py
from django.contrib import admin
from django.urls import path
from todo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.get_todo_list, name='get_todo_list'),
    path('add', views.add_task, name='add'),
    path('edit/<task_id>', views.edit_task, name='edit'),
    path('toggle/<task_id>', views.toggle_task, name='toggle'),
    path('delete/<task_id>', views.delete_task, name='delete'),
]

todo/models.py
from django.db import models

models.Model

# Create your models here.


class Task(models.Model):

    name = models.CharField(max_length=50, null=False, blank=False)
    done = models.BooleanField(null=False, blank=False)

    def __str__(self):
        return self.name

todo/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'done']

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Task
from .forms import TaskForm

# Create your views here.


def get_todo_list(request):
    tasks = Task.objects.all()
    context = {
        'tasks': tasks
    }
    return render(request, 'todo/todo_list.html', context)


def add_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('get_todo_list')

    form = TaskForm()
    context = {
        'form': form
    }
    return render(request, 'todo/add_task.html', context)


def edit_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('get_todo_list')

    form = TaskForm(instance=task)
    context = {
        'form': form
    }
    return render(request, 'todo/edit_task.html', context)


def toggle_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.done = not task.done
    task.save()
    return redirect('get_todo_list')


def delete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.delete()
    return redirect('get_todo_list')

todo/templates/todo/add_task.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Add a ToDo Task:</h1>
    <form method="POST" action="{% url 'add' %}">
        {% csrf_token %}
        <div>
            <p>
                <label for="id_name">Name:</label>
                <input type="text" id="id_name" name="task_name" />
            </p>
        </div>
        <div>
            <p>
                <label for="id_done">Done:</label>
                <input type="checkbox" id="id_done" name="done" />
            </p>
        </div>
        <div>
            <p>
                <button type="submit">Add Task</button>
            </p>
        </div>
    </form>


</body>

</html>

todo/templates/todo/edit_task.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Edit a ToDo Task:</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <p>
                <button type="submit">Update Task</button>
            </p>
        </div>
    </form>


</body>

</html>

todo/templates/todo/todo_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Things to do:</h1>
    <table>
        {% for task in tasks %}
        <tr>
            {% if task.done %}
            <td><strike>{{ task.name }}</strike></td>
            {% else %}
            <td>{{ task.name }}</td>
            {% endif %}
            <td>
                <a href="/toggle/{{ task.id }}">
                    Toggle
                </a>
            </td>

            <td>
                <a href="/edit/{{ task.id }}">
                    Edit
                </a>
            </td>
            <td>
                <a href="/delete/{{ task.id }}">
                    Delete
                </a>
            </td>

        </tr>
        {% empty %}
        <tr>
            <td>You have nothing to do</td>
        </tr>
        {% endfor %}
    </table>
    <a href="/add">Add a Task</a>

</body>

</html>